### PR TITLE
postgresql_set: fix wrong value conversion

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/110

postgresql_set: fix wrong value conversion

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @skilyazhnev @tcraxs

**Review by tcraxs — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@tcraxs thanks for reviewing!

**Comment by Andersson007** [comment]
`community.postgresql` 1.5.0 has been released and is available to install via the `ansible-galaxy` command.
It also contains these changes!

**Pull request merged**
