### PR TITLE
postgresql_user: Get rid of wrong documentation

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/161

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by gundalow** [comment]
@Oloryn Here is a proposed fix

**Comment by Andersson007** [comment]
cc @klando could you please take a look?

**Comment by Andersson007** [comment]
cc @tcraxs ^

**Review by tcraxs — APPROVED** [review]
LGTM

**Comment by Oloryn** [comment]
So, this essentially just deletes the documentation code that can't currently be handled by vscode-ansible, so that vscode-ansible isn't issuing invalid problems in validation.  Should thought be given to instead replacing it with something that vscode-ansible can validate?  E.g., replace the choices with "[ 'SUPERUSER', 'NOSUPERUSER', 'CREATEROLE', 'NOCREATEROLE'," , etc.?  Plus, there is the issue of role_attr_flags is essentially a list expressed as comma-delimited elements in a string.  Would it make sense to make it actually a list, each of whose elements must match the choices (and deal with backwards compatibility issued that would cause - perhaps by adding a role_attr_flags_list that's actually a list, and down the road deprecate role_attr_flags)?

**Comment by Andersson007** [comment]
@Oloryn thanks for the comment

There are several things worth mentioning:
- it would be a breaking change as you said (as a general rule, it's worth avoiding introducing new options that are not really needed)
- different PG versions can have different set of keywords, so it would add a need to keep tracking keywords (the worst case is getting bug reports from users that new keywords are not supported by the module)
- we had trouble with a similar approach (preset of keywords) in c.mysql and we've recently got read of that (such a relief for maintainers and a good thing for users - they just need to read the doc) 

I personally don't see a good reason to introduce a breaking change and additional maintenance burden  / a new option.
So I would just remove wrong-formatted module's doc and refer users to the official doc for PG versions they use.

**Comment by klando** [comment]
> @Oloryn thanks for the comment
> 
> There are several things worth mentioning:
> 
>     * it would be a breaking change as you said (as a general rule, it's worth avoiding introducing new options that are not really needed)
> 
>     * different PG versions can have different set of keywords, so it would add a need to keep tracking keywords (the worst case is getting bug reports from users that new keywords are not supported by the module)
> 
>     * we had trouble with a similar approach (preset of keywords) in c.mysql and we've recently got read of that (such a relief for maintainers and a good thing for users - they just need to read the doc)
> 
> 
> I personally don't see a good reason to introduce a breaking change and additional maintenance burden / a new option. So I would just remove wrong-formatted module's doc and refer users to the official doc for PG versions they use.

agreed.

**Comment by Andersson007** [comment]
@tcraxs @gundalow @klando @Oloryn thanks for reviewing!

**Pull request merged**
