### PR TITLE
add 2.14 to test matrix

### PR DESCRIPTION
**Pull request by hunleyd**
Update test matrix as per [24](https://github.com/ansible-collections/news-for-maintainers/issues/24)

### CODE REVIEW

**Comment by hunleyd** [comment]
is that right @Andersson007 ?

**Comment by Andersson007** [comment]
@hunleyd i think you grabbed a few extra commit that shouldn't be here. Also i think we shouldn't remove 2.11 as it's not EOL.
Could you please fix it, then will see ..how other collections will implement it:))

**Comment by Andersson007** [comment]
i suggest leaving the blank lines there for readability

**Comment by Andersson007** [comment]
@hunleyd we also need to add the same stuff for the code below the `Docker` and `Remote` sections and also add corresponding lines to the list at the bottom of the file

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@hunleyd thanks for the contribution!

**Pull request merged**
