### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Update README.md:
- Update contributing section.
- Add the Code of Conduct and Governance section.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
README.md

### CODE REVIEW

**Comment by Andersson007** [comment]
CC @tcraxs @andytom @kostiantyn-nemchenko @sebasmannem @ilicmilan @popov83
if any ideas on you mind, please add / change

**Comment by Andersson007** [comment]
Folks, I has just also added the `MAINTAINERS` file. I'm sad to see only my login there, so if anyone is interested, feel free to reach me out directly (aaklychkov at mail dot ru).
Ready for review
Thanks

**Comment by tcraxs** [comment]
Thanks @Andersson007 for the energetic and good work. The wording looks good to me.
And beside, please add me to the `MAINTAINERS` file :)

**Comment by Andersson007** [comment]
@tcraxs sure, I'm happy to do it, done! Thank you! BTW did you see an email from me to t at craxs dot de sent on April 21?

**Comment by Andersson007** [comment]
>The wording looks good to me.

@tcraxs thanks for reviewing! (there was another email sent:)

**Pull request merged**
