### PR TITLE
Release 1.7.6 commit

### PR DESCRIPTION
**Pull request by hunleyd**
Release 1.7.6 commit

### CODE REVIEW

**Comment by hunleyd** [comment]
this is that same error where it's finding pg15 and pg14 @Andersson007 . weren't the pipeline fixes backported?

**Review by Andersson007 — APPROVED** [review]
LGTM
https://github.com/ansible-collections/community.postgresql/pull/366 could you please merge it when it's green? You can also backport my clean up PR after that. Then please relaunch tests here

**Comment by Andersson007** [comment]
@hunleyd more strict sanity checks have been recently introduced in devel, so the algorithm will be
1. Review, merge and backport https://github.com/ansible-collections/community.postgresql/pull/367
2. Relaunch tests in https://github.com/ansible-collections/community.postgresql/pull/366, if green, merge it
3. Backport https://github.com/ansible-collections/community.postgresql/pull/363
4. Relaunch tests here. If they are green, feel free to merge (the PR lgtm now). If not, please ping me

thanks!

**Comment by hunleyd** [comment]
> Review, merge and backport Fix sanity errors #367 

.. and the backport failed @Andersson007

**Comment by Andersson007** [comment]
> > Review, merge and backport Fix sanity errors #367
> 
> .. and the backport failed @Andersson007

@hunleyd there was one parameter in the doc fragment I changed that was added in version 2.*, so the conflict happened because it's not in stable-1.
Fixed https://github.com/ansible-collections/community.postgresql/pull/368, feel free to continue:)

**Pull request merged**
