### PR TITLE
Added closing the database connection after completing the task

### LINKED ISSUE #465: postgresql_info not closing connection to database
##### SUMMARY

When using the `postgresql_info` module, it doesn't close the connection to the database. Normally this isn't an issue as the process exits and the connection is terminated that way. However when using mitogen the process does not exit and the connection remains. In my case, it's connecting to the `template1` database, and on a subsequent task when I try to call `postgresql_database` to create a database, it fails with `source database "template1" is being accessed by other users`.

I'm not sure what the thoughts are regarding mitogen, and whether this should be considered a bug on their side, or here.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

postgresql_info

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/phemmer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/phemmer/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/phemmer/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/phemmer/.local/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection           Version
-------------------- -------
community.postgresql 2.4.0  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/phemmer/git/ht/edge/ansible/ht/ansible.cfg
DEFAULT_STRATEGY(/home/phemmer/git/ht/edge/ansible/ht/ansible.cfg) = mitogen_linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/phemmer/git/ht/edge/ansible/ht/ansible.cfg) = ['/home/phemmer/git/mitogen/ansible_mitogen/plugins/strategy']
HOST_KEY_CHECKING(/home/phemmer/git/ht/edge/ansible/ht/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Mitogen 330375b
PostgreSQL 15
Debian 11

##### STEPS TO REPRODUCE

```yaml
- hosts:
    - myhost
  tasks:
    - postgresql_info:
      become_user: postgres
    - postgresql_db:
        name: test
      become_user: postgres

```

##### EXPECTED RESULTS

database created

##### ACTUAL RESULTS

```paste below
TASK [postgresql_db] ****************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DETAIL:  There is 1 other session using the database.
fatal: [myhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "Database query failed: source database \"template1\" is being accessed by other users\nDETAIL:  There is 1 other session using the database.\n"}
```

### PR DESCRIPTION
**Pull request by aleksvagachev**
##### SUMMARY
Fixes #465
Added database connection closure for modules:
- postgresql_ping
- postgresql_info
- postgresql_privs

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Review by Andersson007 — COMMENTED** [review]
@aleksvagachev thanks for the PR! it'd be a great contribution

I suggest:
1. working on the things separately. The changes in all the modules except `postgresql_db` are similar and straightforward. So i suggest moving the `postgresql_db` related stuff to a separate PR as it's more complex case; would be easier to review, easier to revert if needed, etc. What do you think?
2. could you please add the same lines for `postgresql_ping` and `postgresql_privs` to the fragment

thanks

**Comment by aleksvagachev** [comment]
@Andersson007
1) I think you're right
2) It will be done)

**Comment by Andersson007** [comment]
> @Andersson007
> 
> 1. I think you're right
> 2. It will be done)

cool, thanks! please let me know when things are ready for review

**Comment by aleksvagachev** [comment]
@Andersson007 I think you can watch, I rolled back the changes in postgresql_db and will do it in another PR

**Review by Andersson007 — APPROVED** [review]

**Review by hunleyd — APPROVED** [review]

**Pull request merged**
