### PR TITLE
postgresql_query: add as_single_query new option

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/34

Partial revert of https://github.com/ansible-collections/community.general/pull/886

postgresql_query: add `as_single_query` new option

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
`postgresql_query`

### CODE REVIEW

**Comment by Andersson007** [comment]
I'm not sure i chose the best name for the option. Maybe `as_single_query` or something else would be better?

**Comment by Andersson007** [comment]
changed `single_query` to `as_single_query` staying open for other options

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
cc @pmauduit @ilicmilan @kostiantyn-nemchenko @tcraxs

**Review by pmauduit — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@pmauduit thanks for reviewing!

**Pull request merged**
