### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by hunleyd**
##### SUMMARY

For now, set both Andrew and myself as the code owners so that we're tasked w/ reviewing all PRs. Hopefully, in the future, we can add more users and divvy up the repo.

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
@hunleyd LGTM thanks!
Should we backport this for max code consistency?

**Review by tcraxs — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@tcraxs if you wanna be added, just say. We are subscribed anyway but we started this for new contributors. Context: we're going to ask them if they are OK with being added so that they won't miss reports about bugs maybe introduced by their changes, etc. so we'll get more reviews.

**Comment by tcraxs** [comment]
@Andersson007 No thanks, its fine for me :)

**Comment by Andersson007** [comment]
@tcraxs hehe, got it:)

**Pull request merged**
