### PR TITLE
postgresql_db: add support for directory format

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
postgresql_db: add support for directory format

Fixes https://github.com/ansible-collections/community.postgresql/issues/83

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`postgresql_db`

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @tcraxs @kostiantyn-nemchenko

**Comment by Andersson007** [comment]
cc @andytom @landryb

**Comment by landryb** [comment]
i've manually backported the bits added to the 2.7.7+dfsg-1 version i'm using here, and successfully tested a dump/restore via a directory using this snippet:
```
- name: sync databases
  hosts: db
  tasks:
  - name: dump db
    postgresql_db:
      login_password: "{{ postgresql_roles['root']['pass'] }}"
      name: dict_reseaux
      state: dump
      target: /tmp/dict_reseaux.dir

  - name: restore db
    postgresql_db:
      login_password: "{{ postgresql_roles['root']['pass'] }}"
      name: dict_reseaux
      state: restore
      target: /tmp/dict_reseaux.dir
      target_opts: --clean --if-exists
```

thanks !!

**Comment by Andersson007** [comment]
@landryb thanks for testing!

**Comment by Andersson007** [comment]
Do other contributors / maintainers have any ideas?

**Review by tcraxs — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@landryb @tcraxs thanks for reviewing!

**Pull request merged**
