### PR TITLE
Add some basic python code quality practice

### PR DESCRIPTION
**Pull request by l00ptr**
##### SUMMARY
simply trying to use some standard python tool to make the code easier to read.

### CODE REVIEW

**Review by hunleyd — APPROVED** [review]
very nice

**Comment by Andersson007** [comment]
@l00ptr when you're done with this/ there are any questions/difficulties, please let us know. Thanks for pushing forward! (i'm afk today, will be back on Tuesday)

**Comment by Andersson007** [comment]
@l00ptr could you please:
- [Rebase](https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html) the PR
- Fix the tests

**Review by jchancojr — APPROVED** [review]

**Comment by l00ptr** [comment]
finally removed the black part since black no longer support (the dead) python 2.7

**Comment by l00ptr** [comment]
sorry for the delay; it's now ready for a review and merge :)

**Comment by Andersson007** [comment]
Thanks everyone for the contribution!

**Pull request merged**
