### PR TITLE
postgresql_privs: add support for alter default privileges grant usage on schemas

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/332
Fixes https://github.com/ansible-collections/community.postgresql/issues/333

Test task 332 executes the following queries:
```
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM \"ansible_db_user3\";
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO \"ansible_db_user3\"
```
Test task 333 executes the following:
```
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM \"ansible_db_user3\"
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO \"ansible_db_user3\"
```
Is it OK?

`not-specified` is introduced to preserve backwards compatibility, we can change it as a default in a later major release if needed.

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@caseyandgina @hunleyd could you take a look?

@caseyandgina could you please thoroughly test these changes on your test infra?

Despite passing our CI, i won't merge this w/o manual testing (I'm not a DBA).

@hunleyd maybe your folks also could help with testing this?

**Comment by hunleyd** [comment]
this _looks_ ok. will test soon

**Comment by Andersson007** [comment]
> this _looks_ ok. will test soon

@hunleyd thanks, I'll be waiting for your feedback!

**Comment by Andersson007** [comment]
@caseyangdina if you take part in testing I asked for in my [previous message](https://github.com/ansible-collections/community.postgresql/pull/335#issuecomment-1228182638), it'd be much appreciated as we're touching very important module.

**Comment by Andersson007** [comment]
cc @caseyandgina ^

**Comment by caseyandgina** [comment]
@Andersson007 I'm sorry but I really don't know how to test as I'm not a developer.  I'll need some guidance on how to do this.  I have been meaning to talk to some colleagues who have more experience with Ansible, but we've been extremely busy at work lately.

**Comment by Andersson007** [comment]
@caseyandgina sorry for the late reply, was in a business trip, you can test in simply by:
1. finding the location of `plugins/modules/postgresql_privs.py` in your `test` system (copy it somewhere)
2. replacing it with the file from this PR, i.e. with [this one](https://raw.githubusercontent.com/ansible-collections/community.postgresql/a782fa7e4f78386f44193653a8e8d0af22b34f36/plugins/modules/postgresql_privs.py)
3. running the tasks you had issues with before replacing
4. after finishing the tests, you can move the original file back

If you have any questions, feel free to ask
Thank you

**Review by hunleyd — APPROVED** [review]

**Comment by Andersson007** [comment]
@hunleyd @caseyandgina thanks for reviewing!

**Pull request merged**
