### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Update CONTRIBUTING.md

Suggestion not to do it https://github.com/ansible-collections/community.postgresql/pull/763#discussion_r1834397908

### CODE REVIEW

**Review by hunleyd — CHANGES_REQUESTED** [review]
if we're going to do this, we should also nuke the .pre-commit-config.yaml file

personally, i'd rather see us edit the pre-commit-config and rmove whatever it is you don't like/want. I assume it's this:
```
  - id: isort
    name: isort
    entry: isort --check --diff .
    language: system
    types: [python]
```

**Comment by Andersson007** [comment]
@hunleyd SGTM, would you like to do it in another PR? I'll close this one if yes. Let me know

**Comment by hunleyd** [comment]
@Andersson007 i can do that, yes. it'll be at least next week though as i'm having surgery tomorrow

**Comment by Andersson007** [comment]
@hunleyd sure, good luck with the surgery! I wish you recover soon
Created https://github.com/ansible-collections/community.postgresql/issues/768

Closed via https://github.com/ansible-collections/community.postgresql/issues/768

**Pull request closed without merging**
