### PR TITLE
AZP: update matrix

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/595

Closes https://github.com/ansible-collections/community.postgresql/pull/600

- Removes testing against core 2.12 (EOL)
- Removes not supported distros
- Updates distros

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Review by hunleyd — APPROVED** [review]

**Comment by Andersson007** [comment]
same reason: not manually backported tox, etc. PRs..
now i'm backporting this one manually

**Comment by l00ptr** [comment]
Don't we want to drop support for python 2.7 ?  should we adapt our test to use python 3 on CentOS7 ? Currently we still use python2.7 on CentOS 7.

**Comment by Andersson007** [comment]
@l00ptr imo, we should test against it as it's still supported by ansible-core on target hosts https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix

**Pull request merged**
