### PR TITLE
Fix psycopg2 documentation link

### PR DESCRIPTION
**Pull request by zeitounator**
Existing link to psycopg2 documentation has expired. Move to new url

##### SUMMARY

Current expired link: http://initd.org/psycopg/docs/usage.html (tcp error, connection timeout)
Changed to new found link: https://www.psycopg.org/docs/usage.html

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

postgresql_query

##### ADDITIONAL INFORMATION
N/A

### CODE REVIEW

**Review by hunleyd — CHANGES_REQUESTED** [review]
The change doesn't match the PR description. And the old URL works for me, so not sure why it should change. And, iirc, the code prefers psycopg3 now, so pointing at the v2 docs seems incorrect.

**Comment by Andersson007** [comment]
@zeitounator hello, thanks for creating the PR!
@hunleyd it doesn't work for me, there's the timeout. Your note about using v3 sounds fair.
So folks should we maybe use https://www.psycopg.org/psycopg3/docs/ ?

**Comment by zeitounator** [comment]
@hunleyd looks like I made this in a hurry from github gui. The published link yesterday on https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_query_module.html was pointing to https://initd.org whereas the link in main seems to already point to a correct link and as already been pushed to the published documentation. All looks good. Sorry for the inconvenience.

**Comment by Andersson007** [comment]
@zeitounator no worries

**Pull request closed without merging**
