### PR TITLE
correct the pipeline error about 'warn'

### PR DESCRIPTION
**Pull request by hunleyd**
##### SUMMARY

Try to sidestep the pipeline error seen in #227 where the 'warn' arg to
the 'shell' module is claimed to be invalid by splitting the task into
a block/rescue using 'command' and 'yum' instead.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
tests/integration/targets/setup_postgresql_db

### CODE REVIEW

**Comment by Andersson007** [comment]
Looks like another solution is needed

**Comment by hunleyd** [comment]
> Looks like another solution is needed

we're getting past the 'warn' issue and getting a new issue now. looking into it still.

**Comment by Andersson007** [comment]
BTW This PR fixed the issue with `devel`

**Comment by Andersson007** [comment]
The error appears **only** when testing against centos7 AND `ansible-core 2.10` which is also strange.

**Comment by hunleyd** [comment]
ok, so I pulled the docker container in question, and the commands work fine there:
```
sh-4.2# rpm -qa|grep glibc-common
glibc-common-2.17-307.el7.1.x86_64
sh-4.2# ls /usr/share/i18n/charmaps
ls: cannot access /usr/share/i18n/charmaps: No such file or directory
sh-4.2# yum -y reinstall glibc-common || yum -y install glibc-common
[snip
]Installed package glibc-common-2.17-307.el7.1.x86_64 (from CentOS) not available.
Error: Nothing to do
[snip]
]Resolving Dependencies
--> Running transaction check
---> Package glibc-common.x86_64 0:2.17-307.el7.1 will be updated
--> Processing Dependency: glibc-common = 2.17-307.el7.1 for package: glibc-2.17-307.el7.1.x86_64
---> Package glibc-common.x86_64 0:2.17-325.el7_9 will be an update
--> Running transaction check
---> Package glibc.x86_64 0:2.17-307.el7.1 will be updated
--> Processing Dependency: glibc = 2.17-307.el7.1 for package: glibc-headers-2.17-307.el7.1.x86_64
--> Processing Dependency: glibc = 2.17-307.el7.1 for package: glibc-devel-2.17-307.el7.1.x86_64
---> Package glibc.x86_64 0:2.17-325.el7_9 will be an update
--> Running transaction check
---> Package glibc-devel.x86_64 0:2.17-307.el7.1 will be updated
---> Package glibc-devel.x86_64 0:2.17-325.el7_9 will be an update
---> Package glibc-headers.x86_64 0:2.17-307.el7.1 will be updated
---> Package glibc-headers.x86_64 0:2.17-325.el7_9 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================
 Package                   Arch               Version                      Repository           Size
=====================================================================================================
Updating:
 glibc-common              x86_64             2.17-325.el7_9               updates              12 M
Updating for dependencies:
 glibc                     x86_64             2.17-325.el7_9               updates             3.6 M
 glibc-devel               x86_64             2.17-325.el7_9               updates             1.1 M
 glibc-headers             x86_64             2.17-325.el7_9               updates             691 k

Transaction Summary
=====================================================================================================
Upgrade  1 Package (+3 Dependent packages)

Total download size: 17 M
[snip]
Running transaction
  Updating   : glibc-2.17-325.el7_9.x86_64                                                       1/8
  Updating   : glibc-common-2.17-325.el7_9.x86_64                                                2/8
  Updating   : glibc-headers-2.17-325.el7_9.x86_64                                               3/8
  Updating   : glibc-devel-2.17-325.el7_9.x86_64                                                 4/8
[snip]
Updated:
  glibc-common.x86_64 0:2.17-325.el7_9

Dependency Updated:
  glibc.x86_64 0:2.17-325.el7_9                      glibc-devel.x86_64 0:2.17-325.el7_9
  glibc-headers.x86_64 0:2.17-325.el7_9

Complete!
sh-4.2# ls /usr/share/i18n/charmaps
[snip]
]CP771.gz	       IBM1129.gz	    ISO-8859-1.gz	  MAC-UK.gz
```

**Comment by Andersson007** [comment]
Have you run it against `stable-2.10`?

**Comment by Andersson007** [comment]
Just comment `stable-2.10` in the test matrix in this PR. I don't think we should spend much time for this as many collections will stop support 2.9 and 2.10 since May.
I think we should do the same to reduce the maintenance burned and CI load..

**Comment by Andersson007** [comment]
For us, technically, this mean that we'll just remove them from the CI matrix and nothing actually breaking for users will be introduced.
What do you think?

**Comment by Andersson007** [comment]
@hunleyd thanks for the contribution!

**Pull request merged**
