### PR TITLE
Typofix

### PR DESCRIPTION
**Pull request by wschoot**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by hunleyd — APPROVED** [review]

**Comment by hunleyd** [comment]
thanks for making a PR @wschoot !

**Comment by wschoot** [comment]
Anytime! I hate typo's! :)

**Review by Andersson007 — APPROVED** [review]
@wschoot thanks for the fix! @hunleyd thanks for reviewing!

**Comment by Andersson007** [comment]
fyi we have a room on [Matrix](https://docs.ansible.com/ansible/devel/community/communication.html#ansible-community-on-matrix) where users and contributors can share their experience, welcome

**Pull request merged**
