### PR TITLE
ci(azure): update devel images for azure

### LINKED ISSUE #707: Check AZP matrix and update if needed
##### SUMMARY

We should check our AZP [matrix](https://github.com/ansible-collections/community.postgresql/blob/main/.azure-pipelines/azure-pipelines.yml) if we need to change anything wrt https://forum.ansible.com/t/ansible-test-update-remote-and-containers-for-integration-tests/6617

### PR DESCRIPTION
**Pull request by hunleyd**
Update Azure devel images. Closes #707

### CODE REVIEW

**Comment by hunleyd** [comment]
@Andersson007 pg isn't built for ubuntu24 yet. how to proceed? and for fedora40, it looks like `es_ES-x-icu` should be `es-ES-x-icu` ?

**Comment by Andersson007** [comment]
@hunleyd should we tackle them separately then?
I think we should create another issue for Ubuntu 24 with:
1. Add support to the setup target
2. Add it to the matrix as you tried here

For Fedora 40, could you please in this PR add to the assertion `or`, i.e. `"'es_ES-x-icu' in result.stdout_lines[-2]"` -> `"'es_ES-x-icu' in result.stdout_lines[-2]" or "'es-ES-x-icu' in result.stdout_lines[-2]"` ?

**Comment by hunleyd** [comment]
> @hunleyd should we tackle them separately then? I think we should create another issue for Ubuntu 24 with:
> 
>     1. Add support to the setup target
> 
>     2. Add it to the matrix as you tried here
> 
> 
> For Fedora 40, could you please in this PR add to the assertion `or`, i.e. `"'es_ES-x-icu' in result.stdout_lines[-2]"` -> `"'es_ES-x-icu' in result.stdout_lines[-2]" or "'es-ES-x-icu' in result.stdout_lines[-2]"` ?

#713 opened for u24

**Comment by Andersson007** [comment]
@hunleyd FWIW i think you could also try something like:
```
- name: Overwrite icu_locale default value when running on Fedora 40
  when: <put when fedora as distro and 40 as version>
  ansible.builtin.set_facts:
     icu_locale: ...
```

**Review by jchancojr — APPROVED** [review]
lgtm thx doug

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
@hunleyd thanks for the contribution! @jchancojr thanks for reviewing!

**Pull request merged**
