### PR TITLE
postgresql_set: Return a message when a passed parameter has not been found

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/41

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
`postgresql_set`

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Review by tcraxs — APPROVED** [review]
LGTM

only think which could be added is a link to the available config parameters in PostgreSQL Documentation: https://www.postgresql.org/docs/current/runtime-config.html

**Comment by Andersson007** [comment]
@tcraxs agreed, thanks for the idea and the reference! Added

**Comment by tcraxs** [comment]
@Andersson007 Thanks
LGTM

**Comment by Andersson007** [comment]
@davetapley thanks for reporting the issue!
@tcraxs thanks for reviewing!

**Pull request merged**
