### PR TITLE
postgresql_privs - Fixed error message and documentation

### PR DESCRIPTION
**Pull request by RealGreenDragon**
##### SUMMARY

My PR fixes and error message in postgresql_privs module and fixed an error in docs introduced in PR #500 .

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

postgresql_privs

### CODE REVIEW

**Comment by RealGreenDragon** [comment]
Ready for review

**Review by Andersson007 — APPROVED** [review]
@RealGreenDragon LGTM
Just a fyi, generally such changes are considered breaking (as error messages are actually the part of module's interface; someone can check them in playbooks).
We haven't discussed this, so let's not be too strict:)

Whoever will be the next reviewer, if you're ok with this, please merge w/o backporting;)

**Review by hunleyd — APPROVED** [review]

**Comment by hunleyd** [comment]
@Andersson007 merge even w/ 2 failing CI?

**Comment by Andersson007** [comment]
> @Andersson007 merge even w/ 2 failing CI?

@hunleyd sure as it's clearly unrelated (see the call for help on Matrix)

**Comment by Andersson007** [comment]
@RealGreenDragon thanks for the contribution!
@hunleyd thanks for reviewing and merging!

**Pull request merged**
