### PR TITLE
Add missing psycopg2.extras import

### LINKED ISSUE #283: Missing psycopg2.extras import
##### SUMMARY
Attempting to use the task postgresql_query results in an exception "module 'psycopg2' has no attribute 'extras'".

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_query

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.6]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 1.7.2

# /home/user/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
community.postgresql 2.1.5
```

##### CONFIGURATION
```
DEFAULT_FORCE_HANDLERS(/my-project/ansible/ansible.cfg) = True
DEFAULT_FORKS(/my-project/ansible/ansible.cfg) = 2
DEFAULT_GATHERING(/my-project/ansible/ansible.cfg) = explicit
DEFAULT_LOG_PATH(/my-project/ansible/ansible.cfg) = /dev/null
DEFAULT_MODULE_PATH(/my-project/ansible/ansible.cfg) = ['/my-project/ansible/library']
DEFAULT_REMOTE_USER(/my-project/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/my-project/ansible/ansible.cfg) = ['/my-project/ansible/roles', '/etc/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/my-project/ansible/ansible.cfg) = yaml
INJECT_FACTS_AS_VARS(/my-project/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/my-project/ansible/ansible.cfg) = /home/user/.ansible-retry
```

##### OS / ENVIRONMENT
Control host:
Debian Bullseye (debian:bullseye docker image)
python3, python3-pip, python3-psycopg2 (2.8.6) installed using apt
ansible installed using pip3 (ansible==5.7.1)
community.postgresql 2.1.5 installed using ansible-galaxy

Managed host:
Debian Buster (EC2 VM)
python3, python3-psycopg2 (2.7.7) installed using apt

##### STEPS TO REPRODUCE
```yaml
- postgresql_query:
    login_host: "example.com"
    login_user: "example-user"
    login_password: "example-password"
    port: 5432
    ssl_mode: require
    db: "example-db"
    query: 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'
```

##### EXPECTED RESULTS
Query is executed

##### ACTUAL RESULTS
```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/ansible/.ansible/tmp/ansible-tmp-1654252713.6782622-1068-192019440043912/AnsiballZ_postgresql_query.py", line 107, in <module>
    _ansiballz_main()
  File "/home/ansible/.ansible/tmp/ansible-tmp-1654252713.6782622-1068-192019440043912/AnsiballZ_postgresql_query.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ansible/.ansible/tmp/ansible-tmp-1654252713.6782622-1068-192019440043912/AnsiballZ_postgresql_query.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_postgresql_query_payload_69_k5zqt/ansible_postgresql_query_payload.zip/ansible/modules/postgresql_query.py", line 347, in <module>
  File "/tmp/ansible_postgresql_query_payload_69_k5zqt/ansible_postgresql_query_payload.zip/ansible/modules/postgresql_query.py", line 270, in main
AttributeError: module 'psycopg2' has no attribute 'extras'
```

It seems to me that an import for `psycopg2.extras` is missing in this file:
https://github.com/ansible-collections/community.postgresql/blob/a7f68b82ac91cb4884520745891dafcc72c10fa1/plugins/module_utils/postgres.py#L19-L22

And indeed if I execute the following, the problem goes away:
```bash
sed -i 's/    import psycopg2/    import psycopg2\n    import psycopg2.extras/' ~/.ansible/collections/ansible_collections/community/postgresql/plugins/module_utils/postgres.py
```

### PR DESCRIPTION
**Pull request by Joris-van-der-Wel**
##### SUMMARY

On some of our systems the `postgresql_query` task failed with the following error:

    AttributeError: module 'psycopg2' has no attribute 'extras'

Applying the patch from this commit fixed the issue for me on those systems. This was previously reported in issue #283. However now that some time has passed, I am unable to reproduce the issue on our newer systems.

In any case, this is still a mistake that could cause problems in the future, so I think it would be better to fix it.

The reason that this mistake is not causing any actual errors in normal situations is because of how the python import system functions: All of the entrypoints (all the source files under plugins/modules) have an import for `psycopg2.extras`. This causes `extras` to be available on `psycopg2` for any code (in any module) that executes after that import statement, such as the function bodies in `module_utils/postgres.py`.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
community.postgresql

##### ADDITIONAL INFORMATION
Fixes #283

### CODE REVIEW

**Review by Andersson007 — COMMENTED** [review]
@Joris-van-der-Wel thanks for the PR! LGTM

Could you please add a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment) so that our users will see your fix in the collection's changelog?

Thanks

**Review by hunleyd — CHANGES_REQUESTED** [review]
pls re-request review once a changelog fragment has been added. thanks!

**Comment by Andersson007** [comment]
@Joris-van-der-Wel could you please take a look ^. If it's an issue for you, let us know, we merge it as-is and they will add the fragment ourselves

**Review by Andersson007 — APPROVED** [review]

**Review by hunleyd — APPROVED** [review]

**Comment by Andersson007** [comment]
@Joris-van-der-Wel thanks for the contribution! @hunleyd thanks for reviewing and mergin!

@Joris-van-der-Wel if you're not on [Matrix](https://docs.ansible.com/ansible/devel/community/communication.html#ansible-community-on-matrix) yet, you're welcome to join our [room](https://matrix.to/#/#postgresql:ansible.com)!

**Pull request merged**
