### PR TITLE
Add CONTRIBUTING.md with a Quick-start guide

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Add CONTRIBUTING.md with a Quick-start guide

Mostly copied https://github.com/ansible-collections/community.mysql/pull/112

### CODE REVIEW

**Comment by Andersson007** [comment]
CC @tcraxs @andytom @kostiantyn-nemchenko @sebasmannem @ilicmilan @popov83

**Review by kostiantyn-nemchenko — APPROVED** [review]
LGTM

**Review by andytom — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@kostiantyn-nemchenko @andytom thanks for reviewing!

**Pull request merged**
