### PR TITLE
ci(azure pipeline): bump rhel from 9.2 to 9.3 for remote tests

### PR DESCRIPTION
**Pull request by hunleyd**
##### SUMMARY

Implement [#62](https://github.com/ansible-collections/news-for-maintainers/issues/62)

##### ISSUE TYPE

- CI/CD

### CODE REVIEW

**Comment by hunleyd** [comment]
@Andersson007 what's going on w/ the python version error here? did i miss something?

**Comment by Andersson007** [comment]
@hunleyd looks strange. i don't see the other listed collections implemented the change, so hard to say if it's something our collection specific or general. There's a forum discussion attached to the news, so you could publish the error there asking for advice.

**Comment by felixfontein** [comment]
You might have run CI for this one *before* https://github.com/ansible/ansible/pull/82178 got merged (see the "Pending" message at the top of https://github.com/ansible-collections/news-for-maintainers/issues/62). Closing + reopening re-runs CI, I would try that.

**Comment by hunleyd** [comment]
that seems to have been the case @felixfontein, thx!

**Pull request merged**
