### PR TITLE
postgresql_query: a list of queries can be passed

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/312

If we merge it, issues in https://github.com/ansible-collections/community.postgresql/milestones/3.0.0 should be updated

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@felipenazario @hunleyd @betanummeric @jchancojr what do you think about this implementation of https://github.com/ansible-collections/community.postgresql/issues/312 ^

**Comment by felipenazario** [comment]
@Andersson007, Thank you for putting effort into this task.

**Comment by Andersson007** [comment]
@felipenazario thanks for reporting the feature request!
@hunleyd @jchancojr thanks for reviewing!

**Comment by Andersson007** [comment]
@felipenazario we have the [#postgresql:ansible.com](https://matrix.to/#/#postgresql:ansible.com) on [Matrix](https://docs.ansible.com/ansible/devel/community/communication.html#ansible-community-on-matrix). There are also other channels where people share their user/contributor experience. Welcome!

**Pull request merged**
