### PR TITLE
postgresql_user: clarify docs, add debug_info ret var, add integration tests

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/122

postgresql_user: clarify docs, add debug_info ret var, add integration tests

(i don't thing a changelog fragment is needed here)

##### ISSUE TYPE
- Docs Pull Request
- Feature Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Review by zyitingftnt — APPROVED** [review]
tested and solution worked!

**Comment by Andersson007** [comment]
@zyitingftnt thanks for reviewing!

**Comment by Andersson007** [comment]
`community.postgresql` 1.5.0 has been released and is available to install via the `ansible-galaxy` command.
It also contains these changes!

**Pull request merged**
