### PR TITLE
postgresql_membership: add the exact state value to be able to specify a list of only groups a user must be a member of

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/277

##### ISSUE TYPE
- Feature Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@hunleyd @Vanav @jchancojr how about (at least) the interface implementation?
when we pass:
```
postgresql_membership:
  groups: []
  state: exact
  user: blah
```
it'll revoke all groups from a user (i.e. all not listed under `groups`).

**Comment by Vanav** [comment]
Looks good, thank you!

**Comment by hunleyd** [comment]
LGTM

**Comment by Andersson007** [comment]
Ready for review folks.
This time I'll ask to take a look at the code changes please

**Review by hunleyd — APPROVED** [review]

**Comment by Andersson007** [comment]
@hunleyd @Vanav thanks for reviewing!

**Pull request merged**
