### PR TITLE
postgresql_query: fix datetime.timedelta type handling

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.postgresql/issues/47

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
postgresql_query

### CODE REVIEW

**Comment by Andersson007** [comment]
ready_for_review

**Comment by Andersson007** [comment]
recheck

**Comment by Andersson007** [comment]
recheck

**Review by tcraxs — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@tcraxs thank you much for reviewing!

**Pull request merged**
